### ISSUE TITLE
Mistake in clock.js l14?

### ISSUE THREAD

**Issue by lwouis** [Lorti/corsair#1]
https://github.com/Lorti/corsair/blob/84eee120d0f12d09723df828562ac526a8035fbb/src/clock.js#L14

Shouldn't that variable be `previous`. I think currently it merges with initial state continuously

**Comment by Lorti** [comment]
Yes, that should be `previous`. Thank you, I'll fix it right away. 

It makes no difference in the execution, which is why I probably missed it. We could simply return a new state, without merging it with the previous one, as we're overwriting each property. That seems dirty, though.
